### ISSUE TITLE
texture alpha

### ISSUE THREAD

**Issue by syu776** [kiletw/SpineViewerWPF#10]
May I ask what does SpineUsedAlpha do on spine textures? Some skeletons display normally while using SpineUseAlpha instead of PreMultipliedAlpha. What's the difference between SpineUseAlpha and PreMultipliedAlpha? Thanks!

**Comment by kiletw** [comment]
SpineUseAlpha option is spine runtime PremultipliedAlpha option.
PreMultipliedAlpha option is try to fix  pre-multiplied alpha error with xna load texture.

**Comment by syu776** [comment]
I see. Thanks for answering.
