### ISSUE TITLE
Spine Loading Error

### ISSUE THREAD

**Issue by yanagiragi** [kiletw/SpineViewerWPF#2]
Hi,

I tried to use this app to open a spine file, however, I got this.

![default](https://user-images.githubusercontent.com/7404517/46502853-b8a1f100-c85b-11e8-98ad-094e61dfd1d7.png)

The File I tested is
[CharacterSpineL_DorothyCrusher.zip](https://github.com/kiletw/SpineViewerWPF/files/2448130/CharacterSpineL_DorothyCrusher.zip)

Platform: Windows 10 64 bit
SpineViewerWPF Version: v1.0.2.0

**Comment by kiletw** [comment]
畫面往左上拖曳 他只是被介面遮住了
![image](https://user-images.githubusercontent.com/18109554/46512565-40e9bb80-c887-11e8-9af3-b73a9055ea5e.png)
