### ISSUE TITLE
constant crashes and bit laggy

### ISSUE THREAD

**Issue by a44nirig** [kiletw/SpineViewerWPF#20]
This is such a great tool, but sadly it's unusable when it constantly crashes
I think you better off replacing gif export feature with png sequence, I bet it would solve the whole crashing problem
not to mention that big resolutions like 2048 or 4096 make the tool very laggy and the output gif fps becomes way slower compared to 1024.
so png sequence or any video format could be the solution

**Comment by kiletw** [comment]
v2.4.0.0 add export type png sequence.
