### ISSUE TITLE
Why the package have so may  versions of spine 

### ISSUE THREAD

**Issue by TruePluto** [kiletw/SpineViewerWPF#23]
As the title . I don't understand the reason about multiple versions of spine. 
And I want to know whether these versions are necessary. or I can just keep one version for my specify atlas file.
Thank you

**Comment by yanagiragi** [comment]
The multiple versions may not necessary in your case, it does needed in my case. In my scenario, I had to tweek the versions for different spines, since those spines are ripped from game therefore I may not know the proper version to open it.

**Comment by Blue-Roar** [comment]
Actually you can remove the unneeded libraries by yourself
