### ISSUE TITLE
感谢作者！查看动画很方便，但导出gif时总是发生崩溃

### ISSUE THREAD

**Issue by hatsunoyuki** [kiletw/SpineViewerWPF#25]
在导出大于128x128的gif文件时会crash，基本上只有使用4-bit导出不会崩溃，请问有解决的方法吗？

**Comment by kiletw** [comment]
試試看把Use Disk Cache勾選，我猜測是內存不足導致崩潰。

**Comment by hatsunoyuki** [comment]
> 試試看把Use Disk Cache勾選，我猜測是內存不足導致崩潰。

感谢回复，我试着将其他程序都关掉之后，可以导出更大的文件了🙇‍♂️

**Comment by hatsunoyuki** [comment]
> 試試看把Use Disk Cache勾選，我猜測是內存不足導致崩潰。

感谢回复，我试着将其他程序都关掉之后，可以导出更大的文件了🙇‍♂️
