### ISSUE TITLE
[Feature Request]  Gif export with Transparent BG

### ISSUE THREAD

**Issue by ourlib** [kiletw/SpineViewerWPF#27]
thx. i'm bad at coding.

**Comment by yanagiragi** [comment]
GIF doesn't have an alpha channel. You need a [webp](https://en.wikipedia.org/wiki/WebP).

**Comment by ourlib** [comment]
> GIF doesn't have an alpha channel. You need a [webp](https://en.wikipedia.org/wiki/WebP).

oh, sorry for the description. i mean transparent bg. seems the AnimatedGif lib does not provide it.

**Comment by yanagiragi** [comment]
I think the alpha channel and transparent BG means the same thing. So what I mean is that perhaps you should request a alternative export format to support "transparent animations".

**Comment by kiletw** [comment]
https://github.com/kiletw/SpineViewerWPF/releases/tag/2.4.0.0
