### ISSUE TITLE
3.8.99 spine file displays incorrectly

### ISSUE THREAD

**Issue by ghost** [kiletw/SpineViewerWPF#28]
I have 3.8.99 files, they can be opened with the 3.8.95 option (other versions just crash the program)
however, there's visible seam lines that shouldn't be there
![capture](https://user-images.githubusercontent.com/28833142/191917262-61877c26-1488-4c41-bdf2-c916c9f918b2.JPG)
changing attribute options doesn't solve the problem

**Comment by kiletw** [comment]
Please upload spine file.

**Comment by ghost** [comment]
[spine.zip](https://github.com/kiletw/SpineViewerWPF/files/9639846/spine.zip)
here's the file
thanks in advance

**Comment by kiletw** [comment]
![image](https://user-images.githubusercontent.com/18109554/192213999-4d2766c8-8f15-4029-8bf9-81e827fda5d1.png)
click those option is work fine.

**Comment by ghost** [comment]
damn I swear to god I messed with those optioins, never tried both together I guess lol
sorry for wasting your time and thank you very much
