### ISSUE TITLE
將 lb_PosX 以及 lb_PosY 改為 TextBox

### ISSUE THREAD

**Issue by yanagiragi** [kiletw/SpineViewerWPF#3]
您好，

首先謝謝你提供了這麼棒的程式。

然而在使用者體驗上，想向您詢問一下是否有考慮把 lb_PosX 以及 lb_PosY 這兩個欄位改為 TextBox 呢?

主要的理由是有時候要拖曳很久 (例如: [issues/2](https://github.com/kiletw/SpineViewerWPF/issues/2))

如果不介意，我有簡單寫了一個修改過的 [版本](https://github.com/kiletw/SpineViewerWPF/compare/master...yanagiragi:master)

不過我也必須說我對C# 沒有那麼熟悉，也對自己的code 沒什麼自信。

造成你的困擾很不好意思。謝謝您。

**Comment by kiletw** [comment]
已更新

**Comment by yanagiragi** [comment]
剛剛看到了！感謝 💯
