### ISSUE TITLE
can you add 3.3.05 version?

### ISSUE THREAD

**Issue by K88-ko** [kiletw/SpineViewerWPF#4]
..

**Comment by kiletw** [comment]
I think use 3.4.02 version can work fine on 3.3.05 spine file.

**Comment by K88-ko** [comment]
i want see this spine T.T
langrisser mobile game
[Lana.zip](https://github.com/kiletw/SpineViewerWPF/files/4177907/Lana.zip)

**Comment by kiletw** [comment]
You have to process the png file to composite the transparent channels.
Luna.png with Luna_a.png

![Lana](https://user-images.githubusercontent.com/18109554/74119704-96607600-4bfb-11ea-9efb-c1ecdae96522.png)


![image](https://user-images.githubusercontent.com/18109554/74119587-14704d00-4bfb-11ea-9d6f-009ee2cc0475.png)

**Comment by K88-ko** [comment]
wow awesome
can you teach me  png file to composite the transparent channels.
and i try load spine 
<img width="390" alt="33" src="https://user-images.githubusercontent.com/59752477/74132529-1ac9ed80-4c2a-11ea-8ada-3513539f28a9.png">

**Comment by K88-ko** [comment]
oh... thank you
i realize mean!!!!!!
![111](https://user-images.githubusercontent.com/59752477/74159631-6cd93600-4c5f-11ea-8f97-2dde82333f14.PNG)


谢谢先生
