### ISSUE TITLE
无法导出正确图像

### ISSUE THREAD

**Issue by sxjeru** [kiletw/SpineViewerWPF#5]
`I guess from “_(:3」∠)_” that you can understand Chinese. If not, I will provide English version for you and sorry.`

首先感谢作者制作这个预览器，给吾等买不起 Spine 的穷人提供了便利。

进入正题。
我用本软件加载了一个 spine atlas，预览界面也有正确的显示。
https://i.loli.net/2020/04/16/ma5DxZfgrnoNvLJ.png

但单击下方“相机”图标，选择保存路径后只得到下图。
https://i.loli.net/2020/04/16/sURXw74mzcqPxye.png

已尝试更改Version，无效。

json文件中提到的Spine版本号为`3.7.93`。

**Comment by sxjeru** [comment]
另外下方的“录像机”图标，应该是用来录制GIF的吧。
按下后会从头开始播放，但播放一次后无事发生。第二次按下后程序无响应，随后崩溃。

按一次“录制”再按“截图”也会崩溃。
希望作者能解决一下。

**Comment by kiletw** [comment]
上傳檔案給我測試處理

**Comment by sxjeru** [comment]
[Ch001.zip](https://github.com/kiletw/SpineViewerWPF/files/4490608/Ch001.zip)
感谢回应。

**Comment by kiletw** [comment]
已解決 重新抓新版就好

**Comment by sxjeru** [comment]
图像问题证实已解决，再次感谢。
不过有关GIF还是无法生成。是我的用法不对还是……？
`症状：程序无响应 随后退出，或导出1字节大小损坏的GIF文件。`
`崩溃前大量占用内存，导致无响应。`

**Comment by kiletw** [comment]
可能是爆內存
暫時還沒有好的想法

**Comment by sxjeru** [comment]
OK，关掉Chrome后提取成功了。

`以为“重新抓取”就是重新构建，火急火燎搭建了C# build，结果发现 release 虽然显示19 Jan，但Assets
已经更新过了...... 瞬间感觉智商欠费了一样。`
