### ISSUE TITLE
Fullscreens interfere the program

### ISSUE THREAD

**Issue by Blue-Roar** [kiletw/SpineViewerWPF#7]
Fullscreens, e.g. the lockscreen and the Ctrl+Alt+Del stopscreen seem to interfere the program - the main window just disappears, and LoadPlayer() does not work at all since then...

**Comment by BrightSu02** [comment]
Windows 10 1909

**Comment by BrightSu02** [comment]
Windows 10 1909

**Comment by kiletw** [comment]
fix. Maybe there are other good ways to solve this problem.
