### ISSUE TITLE
Spine crashes

### ISSUE THREAD

**Issue by chrrox** [kiletw/SpineViewerWPF#9]
This crashes your viewer (NSFW)
[53_duoSwordAngelGirl.zip](https://github.com/kiletw/SpineViewerWPF/files/5638902/53_duoSwordAngelGirl.zip)

**Comment by kiletw** [comment]
Because of  Spine 3.8.75 had a cracked version.So EsotericSoftware set the spine runtime can not work on 3.8.75 version.
I will fix it.

**Comment by kiletw** [comment]
You can open json file edit 3.8.75 to 3.8.76 or other version.
Maybe it will work.

**Comment by kiletw** [comment]
fix.

**Comment by saiffyros** [comment]
That's funny. They actually have a line of code for that in skeleton binary lol: if ("3.8.75" == skeletonData.version)
					throw new Exception("Unsupported skeleton data, please export with a newer version of Spine.");

**Comment by R8bert** [comment]
> That's funny. They actually have a line of code for that in skeleton binary lol: if ("3.8.75" == skeletonData.version) throw new Exception("Unsupported skeleton data, please export with a newer version of Spine.");

can you get rid of the error and use 3.8.75 in unity?

**Comment by saiffyros** [comment]
I haven't tried with Unity, but it worked with MonoGame 10 months ago when I tested it.

**Comment by 21-brother** [comment]
> 
export json,edit it, change 3.8.75 to 3.8.9 ,works with me

**Comment by 21-brother** [comment]
> > 这很有趣。他们实际上在骨架二进制lol中有一行代码：如果（“3.8.75” == skeletonData.version）抛出新的异常（“不支持的骨架数据，请使用较新版本的Spine导出。
> 
> 你能摆脱错误并使用3.8.75团结吗？

export json,edit it, change 3.8.75 to 3.8.9 ,works with me

**Comment by Artem29383** [comment]
on 3.8.9 i have a truble with rendering in URP, when switch to 3.8.96  it fix and works well
